[package]
name = "n-puzzle"
version = "0.1.0"
edition = "2021"
authors = ["Alexandre Delille <adelille@student.42.fr>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
byte-unit = "4.0.12"
